---
- hosts: main
  tasks:

  - name: Install packages
    apt:
      name: {{ item }}
      state: latest
      update_cache: true
    loop:
      - nginx
      - docker
      - docker-compose

#  - name: install nginx
#    apt:
#      name: nginx
#      state: latest
#
#  - name: install docker
#    apt:
#      name: docker
#      state: latest
#
#  - name: install docker-compose
#    apt:
#      name: docker-compose
#      state: latest
#      update_cache: true

  - name: docker status 
    service:
      name: docker
      state: started
      enabled: yes

  - name: create user and add in docker's group
    ansible.builtin.user:
      name: alex
      shell: /bin/bash
      groups: docker
      append: yes

  - name: show nginx version
    command: nginx -v
    register: nginx_version

  - name: print version
    debug: 
      msg: "NGINX VERSION: '{{ nginx_version.stderr }}'"
